# Generated by Django 2.2.2 on 2019-06-18 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money_record', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Money_recored',
            new_name='Money_record',
        ),
    ]
