# Generated by Django 2.2.2 on 2019-06-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_record', '0002_auto_20190618_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money_record',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
