# Generated by Django 2.2.2 on 2019-06-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_record', '0004_auto_20190622_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money_record',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
