# Generated by Django 2.2.2 on 2019-06-22 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_record', '0005_auto_20190622_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money_record',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
